[project]
name = "nuki"
version = "0.3.0.beta"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yann Querlioz", email = "zazbone@pm.me" }
]
requires-python = ">=3.12"
dependencies = [
    "array-api-compat>=1.11.2",
    "numpy>=2.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "ruff>=0.9.10",
]
